added optional enforcing for certain orientation
FilledStacks/responsive_builder pull request #11
Opened 2020-04-03 20:47 UTC by jakobwgnr

This PR adds an optional functionality to enforce a certain orientation in OrientationLayoutBuilder which might be a nice little feature when dealing with layouts.

In addition there was some automatic formatting done by the IDE as well as a few updates to the pubspec.yaml. Hope that is fine

2022-01-31 11:03 UTC, Gerrel commented
@FilledStacks would like to see these enforce properties on OrientationLayoutBuilder so that I can for example enforce portrait layout on mobile without doing some extra if-statements and anonymous builder functions.

2022-02-01 13:52 UTC, FilledStacks requested changes
I like the PR. There's a few changes I'd like. 

1. Better exception messages
2. Clear indication of system wide side effects being invoked.

2022-02-01 13:52 UTC, FilledStacks commented on lib/responsive_builder.dart
> +          'Choose either enforcing both orientations is not an option');
Please change this to "Cannot enforce portrait and landscape. Only one can be set to true"

2022-02-01 13:52 UTC, FilledStacks commented on lib/responsive_builder.dart
> +      SystemChrome.setPreferredOrientations([
This will cause unintended side effects which I am not comfortable with. I think orientation lock should always be explicit in the app that's implementing it. 

I'm leaning towards removing this line, but I think it fits the mission of improving the layout experience in Flutter code bases. 

We can add another property called `lockDeviceOrientation` which if also set to true will execute this code. If false we don't run this.

2022-02-01 13:52 UTC, FilledStacks commented on lib/responsive_builder.dart
> +        throw new Exception('variable portrait required');
Change message to "When enforcePortrait is true, portrait builder has to be supplied to the OrientationLayoutBuilder"

2022-02-01 13:52 UTC, FilledStacks commented on lib/responsive_builder.dart
> +      SystemChrome.setPreferredOrientations([DeviceOrientation.landscapeLeft]);
Refer to message above. This should also be behind the `lockDeviceOrientation` boolean property.

2022-02-01 13:52 UTC, FilledStacks commented on lib/responsive_builder.dart
> +        throw new Exception('variable landscape required');
Change message to "When enforceLandscape is true, landscape builder has to be supplied to the OrientationLayoutBuilder"

2022-02-01 13:52 UTC, FilledStacks commented on CHANGELOG.md
> +
Please move this to above the version above.

2022-02-13 15:37 UTC, Gerrel commented
@FilledStacks I’ll create a new PR.

2022-02-13 16:25 UTC, Gerrel commented
@FilledStacks  This PR can be closed I've created the new PR: #38  https://github.com/FilledStacks/responsive_builder/pull/38

2022-02-13 16:58 UTC, jakobwgnr commented
@Gerrel appreciated

2022-02-14 07:24 UTC, closed without merging

2022-02-14 07:28 UTC, FilledStacks commented
Published @Gerrel