migrate to null-safety
FilledStacks/responsive_builder pull request #23
Opened 2021-01-18 18:46 UTC by bierbaumtim

fixes #22

2021-01-19 08:07 UTC, FilledStacks requested changes
Thanks for the PR. Just one thing that I'd like changed back and that's using the normal UI builder as the default builder instead of the small UI builder.

2021-01-19 08:07 UTC, FilledStacks commented on lib/src/widget_builders.dart
> +    required this.small,
Please make normal required and not small. the normal view is what you want to show if there's no UI defined.

2021-01-19 08:07 UTC, FilledStacks commented on lib/src/widget_builders.dart
> +        return small(context);
Change back to using the normal function when there's nothing defined.

2021-01-19 16:50 UTC, bierbaumtim commented
The problem is that if normal is required, the small function never gets used, because the normal function can't be null. So this will make the small function useless.
To solve the problem we should introduce a RefinedSize.small. With this we can check if the size is RefinedSize.small and than use the small one.

2021-01-20 08:21 UTC, FilledStacks commented
You're right. Then we can instead update the case before the final return to check for small and then return the small() in there. Then we can leave the default if nothing is defined to return normal()

2021-01-21 06:15 UTC, FilledStacks approved these changes
Great!

2021-01-21 06:17 UTC, merged

2021-01-21 06:22 UTC, FilledStacks commented
@bierbaumtim Thanks a lot for the help! I've published it.