Add `isWebOrDesktop` to ResponsiveBuilder
FilledStacks/responsive_builder pull request #36
Opened 2021-10-15 19:33 UTC by georgeherby

Fixes #31

Fixes the issues on all Desktop platforms when the window is wider than the height and mean it used the tablet sizes. 

This change ensures that width=Size.width rather than width=Size.shortest when on Web and Desktop. The code was there in the getDeviceTypes and getRefindedSize but it was either was not configurable and stuck as kIsWeb or had a parameter and defaulted. I have added a parameter to ResponsiveBuilder to allow this to be overridden. Currently, it just defaults to kIsWeb as this was the existing behaviour.

Example
```
ResponsiveBuilder(
      isWebOrDesktop: kIsWeb || Theme.of(context).platform.isDesktop(), // Using an extension function to determine isDesktop
      builder: (context, sizingInformation) {
 ...
}
```

Extra. If anyone wants the extension function to use the above
```
extension PlatformCheck on TargetPlatform {
  bool isDesktop() {
    return [TargetPlatform.macOS, TargetPlatform.windows, TargetPlatform.linux]
        .contains(this);
  }
}
```

2021-10-18 06:43 UTC, FilledStacks requested changes

2021-10-18 06:43 UTC, FilledStacks commented on CHANGELOG.md
> +## Unreleased
Please change this to 0.4.1

2021-10-18 06:43 UTC, FilledStacks commented on lib/src/helpers.dart
> +  bool? isWebOrDesktop,
this implementation means you have to pass this in for every single use of the functions or widgets. I think flutter has a boolean built in to determine this. Similar to `kIsWeb` which we can use

2021-12-30 15:24 UTC, georgeherby commented on lib/src/helpers.dart
> +  bool? isWebOrDesktop,
It is not required, it is an optional value so if not provided acts as before using the kIsWeb. 

I am not aware of a constant that does such - I believe there is only a constant for web?

2024-05-17 20:00 UTC, closed without merging