Added Desktop platform checks.
FilledStacks/responsive_builder pull request #37
Opened 2021-11-17 13:56 UTC by disparta

Fixes #31 
#36 requires the developer to parse a variable to the ResponsiveBuilder.

On Desktop (Windows and macOS - I did not test Linux), the tablet builder would be used even when in full-screen mode. This however did not happen in Web. 

I added the following because I did not want to depend on universal_io. This uses dart:io (which is not supported on the web). It is only called when the app is compiled for desktop, mobile, and not web.

` if (kIsWeb) {
    deviceWidth = size.width;
  } else {
    //Check if the device is a desktop, should not be web
    if (Platform.isMacOS || Platform.isWindows || Platform.isLinux) {
      deviceWidth = size.width;
    }
  }`

2023-02-03 20:01 UTC, meysammahfouzi commented on lib/src/helpers.dart
> +    }
Why not put all of them in one `if()` statement?

```suggestion
    if (kIsWeb || Platform.isMacOS || Platform.isWindows || Platform.isLinux) { 
      deviceWidth = size.width;
    }
```

2023-02-08 12:56 UTC, FilledStacks commented on lib/src/helpers.dart
> +    }
Good suggestion.

2023-02-08 12:57 UTC, FilledStacks submitted a review, later dismissed
Awesome. I will merge, bump version and change log and release.

2023-02-08 13:00 UTC, FilledStacks requested changes
Using dart:io package will remove the support for flutter web. I think 🤔  Could you please double check it still works for flutter web. 

In addition please bump the patch version and also add it into the changelog.

2023-02-08 13:38 UTC, disparta commented
It works. I've been using it in production on Web and haven't seen an issue.

2023-02-10 09:22 UTC, merged